Implemented Lasso and Ridge Regularization
PEC-CSS/slowmokit pull request #106
Opened 2023-02-13 15:01 UTC by YashitaBansal

2023-02-13 19:58 UTC, ken1000minus7 requested changes

2023-02-13 19:58 UTC, ken1000minus7 commented on src/slowmokit/methods/linear_model/lasso_regularization.cpp
> +  double L = 0.0;
Write a more descriptive variable name and use camel case

2023-02-13 19:58 UTC, ken1000minus7 commented on src/slowmokit/methods/linear_model/lasso_regularization.cpp
> +    double y_pred = 0.0;
camel case as always

2023-02-13 19:58 UTC, ken1000minus7 commented on src/slowmokit/methods/linear_model/ridge_regularization.cpp
> +  //   return yPred;
Delete these lines if not required, do not keep commented code anywhere

2023-02-13 19:58 UTC, ken1000minus7 commented on src/slowmokit/methods/linear_model/ridge_regularization.cpp
> +  double y_pred = coefficients[0];
camel case as always

2023-02-13 20:00 UTC, Ishwarendra requested changes

2023-02-14 13:47 UTC, ken1000minus7 commented
Write `Loss` in camel case i.e. `loss`

2023-02-14 15:36 UTC, ken1000minus7 approved these changes
Lgtm

2023-02-18 07:45 UTC, closed without merging