knn_model
PEC-CSS/slowmokit pull request #31
Opened 2023-01-25 19:09 UTC by Sar-thak-3

Added python knn model at src/slowmokit/models/knn.hpp

2023-01-27 06:02 UTC, UtkarshGoelUT commented
Hey 
Please refer to the linear regression model to see the best practices and try to implement those. 
```
https://github.com/PEC-CSS/slowmokit/tree/main/src/slowmokit/methods/linear_model/linear_regression
```
Also, could you try adding a single model per PR?

2023-01-27 06:04 UTC, UtkarshGoelUT commented
Also for each of the models you add, kindly add example for the same. Refer to linear regression model. 
```
https://github.com/PEC-CSS/slowmokit/blob/main/examples/linear_models/linear_regression.cpp
```

2023-01-27 08:56 UTC, ken1000minus7 requested changes

2023-01-27 08:56 UTC, ken1000minus7 commented on src/slowmokit/models/Kmeans.hpp
> +using namespace std;
Do not use `using namespace std` anywhere, use `std::` wherever applicable instead

2023-01-27 08:56 UTC, ken1000minus7 commented on src/slowmokit/models/bernoulliNB.hpp
> +    double prior_prob(vector<int> y_train,int label){
According to our guidelines variables and function names should be in camel case **not** snake case

2023-01-27 08:59 UTC, harshjohar requested changes
## Following changes must be done before PR
- Fix the directory structure according to the mentioned conventions in [README.md](../../README.md)
- Use a IDE like CLion, to automatically configure CMake, otherwise, configure it yourself
- use `hpp` files only to declare functions, all the definitions must be done in the `cpp` file.
- The following is the correct directory structure for a new model

> DO NOT USE `use namespace std;`

```
src
  -slowmokit
    - methods
      - <Model type>
         - <Model Name>/
         - <Model Name>.hpp
```

2023-01-28 03:18 UTC, uttammittal02 requested changes
You didn't make use of the variable 'k' in the code of kNN passed as a parameter in the function predict.
Review Line 25 of this file

2023-01-30 14:04 UTC, UtkarshGoelUT commented
> Can you please guide me how do I now, test the working of all models prepared according to the structure defined in README.md , as I never worked with Clion?

Create a file in the examples folder, and run that file.
Refer to the [linear regression example](https://github.com/PEC-CSS/slowmokit/blob/main/examples/linear_models/linear_regression.cpp) for the same.

2023-01-31 08:26 UTC, closed without merging