Implemented Classification Report #55
PEC-CSS/slowmokit pull request #73
Opened 2023-02-06 17:36 UTC by Modernbeast02

Implemented Classification Report and Resolved Issue #55 

This is how the table will be printed. 

<img width="502" alt="Screenshot 2023-02-06 at 11 05 55 PM" src="https://user-images.githubusercontent.com/89138051/217043913-a0b38cea-cc3f-46f6-908c-8a740d47a183.png">

2023-02-06 18:22 UTC, ken1000minus7 requested changes

2023-02-07 03:50 UTC, uttammittal02 requested changes
Make all the required changes

2023-02-07 03:50 UTC, uttammittal02 commented on src/slowmokit/methods/metrics/classification_report.hpp
> +    std::map<T, T> classes, truePositive, falsePositive, trueNegative, falseNegative;
Change these maps to map<T, int> as count will always be an integer no matter what input arrives

2023-02-07 03:50 UTC, uttammittal02 commented on src/slowmokit/methods/metrics/classification_report.cpp
> +        int classNumber = it.first;
type of it.first is T and not int. This is done at some other places too....see and correct it

2023-02-07 03:50 UTC, uttammittal02 commented on src/slowmokit/methods/metrics/classification_report.cpp
> +        precisionMap[classNumber] = (double)(truePositive[classNumber] / (double)(truePositive[classNumber] + falsePositive[classNumber]));
Ig this might give error if both TP and FP for the concerned class are 0. Similar case for recall too

2023-02-07 03:50 UTC, uttammittal02 commented on src/slowmokit/methods/metrics/classification_report.cpp
> +int main()
Shift this main function to the example file

2023-02-07 03:50 UTC, uttammittal02 commented on src/slowmokit/methods/metrics/classification_report.cpp
> +    Class.confusionMatrix(trueValue, predictedValue);
Ig u should call this function in the constructor itself

2023-02-07 06:02 UTC, closed without merging