Multiclass Logistic Regression Model
PEC-CSS/slowmokit pull request #80
Opened 2023-02-07 14:02 UTC by Sar-thak-3

2023-02-08 03:47 UTC, harshjohar requested changes
Do the following steps
- pull the latest commit from `main` branch
- resolve any conflicts
- run the script as mentioned the `README.md` point 9 to format the spacing and everything properly

2023-02-08 05:22 UTC, Sar-thak-3 commented
> * run the script as mentioned the `README.md` point 9 to format the spacing and everything properly
Sir should i Run "./clang-format-all src/" this command directly in my vs code terminal?

2023-02-08 06:25 UTC, uttammittal02 commented
> > * run the script as mentioned the `README.md` point 9 to format the spacing and everything properly
> >   Sir should i Run "./clang-format-all src/" this command directly in my vs code terminal?

Yes run it in the directory of your cloned repo

2023-02-08 06:27 UTC, harshjohar commented
> > * run the script as mentioned the `README.md` point 9 to format the spacing and everything properly
> 
> Sir should i Run "./clang-format-all src/" this command directly in my vs code terminal?
> 
> 

If you have mac or linux then directly in terminal, but if you have windows, you gotta run this in git bash in the project root directory

2023-02-08 07:28 UTC, Sar-thak-3 commented
> > > * run the script as mentioned the `README.md` point 9 to format the spacing and everything properly
> > 
> > 
> > Sir should i Run "./clang-format-all src/" this command directly in my vs code terminal?
> 
> If you have mac or linux then directly in terminal, but if you have windows, you gotta run this in git bash in the project root directory

![Screenshot 2023-02-08 125736](https://user-images.githubusercontent.com/100359818/217462626-d50f032b-6009-49e3-81de-f1094e4630c9.png)

2023-02-08 07:39 UTC, harshjohar approved these changes
lgtm

2023-02-08 09:15 UTC, ken1000minus7 approved these changes
Lgtm gw

2023-02-08 11:07 UTC, uttammittal02 requested changes
Doesn't seem upto mark

2023-02-08 11:21 UTC, Sar-thak-3 commented
> Doesn't seem upto mark

Kindly review the changes

2023-02-08 11:24 UTC, uttammittal02 commented
> > Doesn't seem upto mark
> 
> Kindly review the changes

Bro the code isn't readable...aake bta ke ja ki kya kr rha....variable names thode readable rakh....Add some comments too

2023-02-08 11:54 UTC, harshjohar approved these changes
Lgtm

2023-02-08 12:32 UTC, uttammittal02 commented
@Sar-thak-3 Refer these [docs](https://github.com/PEC-CSS/slowmokit/blob/main/docs/methods/linear_model/linear_regression.md) for reference and add similar docs for your code

2023-02-08 15:07 UTC, Ishwarendra commented on docs/methods/linear_model/logistic_regression.md
> +Logistic Regression model using stocastic gradient descent.
Typo: `stochastic` instead of `stocastic`

2023-02-08 15:22 UTC, uttammittal02 requested changes
Good job....just a few more changes

2023-02-08 15:22 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +  std::vector<double> values(x.size());
Remove this vector declaration

2023-02-08 15:22 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +    l += (y[i] * qi[i]);
It should be `y[i] * log(q[i])` here. Read about logloss function used for logistic regression

2023-02-08 15:22 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +LogisticRegression<T>::logRegSgd(std::vector<std::vector<double>> x,
Take user parameter `batch_size` and do the training in batches

2023-02-08 15:22 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +void LogisticRegression<T>::train(std::vector<std::vector<T>> x,
We'll be assuming that user won't provide onehot-encoded labels. You need to do that inside your code

2023-02-08 18:41 UTC, uttammittal02 requested changes
Add docs for Gaussian NB and KNN also

2023-02-08 18:41 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +    l += (y[i] * log10(qi[i]));
Use natural log here

2023-02-09 06:53 UTC, uttammittal02 requested changes
A few more changes

2023-02-09 06:53 UTC, uttammittal02 commented on docs/methods/linear_model/logistic_regression.md
> +Logistic Regression model using stochastic gradient descent.
It's mini-batch gradient descent and not stochastic.

2023-02-09 06:53 UTC, uttammittal02 commented on docs/methods/linear_model/logistic_regression.md
> +| Batch size    |  Number of x values in batch over which loss will be computed and weights will be updated   | 5        | `int`    |
Change the default batch size to 10% of the whole dataset

2023-02-09 06:53 UTC, uttammittal02 commented on docs/methods/linear_model/logistic_regression.md
> +| `crossEntropy(vector<int>y,vector<T>qi)` | actual*predicted value                       | DOUBLE       |
`actual * log(predicted)` and not `actual * predicted`

2023-02-09 06:53 UTC, uttammittal02 commented on docs/methods/linear_model/logistic_regression.md
> +| `logRegSgd(vector<vector<double>>x,vector<vector<int>>y,double alpha,int numEpochs,bool verbose)`| Performs logistic regression  |      `vector<vector<T>>`      |
Change the name for this function also accordingly

2023-02-09 06:53 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +void LogisticRegression<T>::train(std::vector<std::vector<T>> x,
You need not write your own one-hot encoder. Use the one already written in our library. Also change the name of `train` function to `fit`

2023-02-09 06:53 UTC, uttammittal02 commented on docs/methods/linear_model/logistic_regression.md
> +| `logRegSgd(vector<vector<double>>x,vector<vector<int>>y,double alpha,int numEpochs,bool verbose)`| Performs logistic regression  |      `vector<vector<T>>`      |
Also, add the batch_size parameter here and also in the example below

2023-02-09 06:53 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +    std::vector<std::vector<double>> gradLi( // Initializing gradient descent
Declare this vector inside the while loop itself to avoid emptying it each time

2023-02-09 06:53 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +      if ((prm.size() + countCompleted) <
This isn't how it actually works.
In each epoch, you need to choose a random value (the starting point of that batch) and take a batch of the given size from that....many training inputs might be considered multiple times in such a case.

2023-02-09 06:53 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +  std::vector<std::vector<double>> beta(
Initialise betas with random values instead of zeros

2023-02-09 06:53 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.hpp
> +   * @brief Logistic regression
Change it to `Mini-batch gradient descent`.
Also, add the batch-size parameter here

2023-02-09 09:18 UTC, uttammittal02 requested changes
Some old changes are left and one or two new changes have been requested

2023-02-09 09:18 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
> +  this->batchSize = batchSize;
where did you set the default value for the batch_size

2023-02-09 10:32 UTC, uttammittal02 requested changes
Just some last changes

2023-02-09 10:32 UTC, uttammittal02 commented on docs/methods/linear_model/logistic_regression.md
> +| Batch size    |  Number of x values in batch over which loss will be computed and weights will be updated   | 5        | `int`    |
@Sar-thak-3 do it bro

2023-02-09 10:32 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.hpp
> +   * @param batchSize size of match
match?

2023-02-09 10:32 UTC, uttammittal02 commented on src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.hpp
> +   * @return std::vector<double> one hot encoded probobabilities for each class
fix the typo in `probobabilities`

2023-02-09 10:55 UTC, uttammittal02 approved these changes
Lgtm....op work

2023-02-09 10:56 UTC, merged