Implemented precision and recall for a multiclass classifier #38
PEC-CSS/slowmokit pull request #82
Opened 2023-02-07 15:45 UTC by YashitaBansal

Input:
`vector<int> prediction = {0, 1, 2, 1, 0, 2, 1, 0, 1, 2}
  vector<int> actual = {0, 0, 2, 1, 0, 2, 1, 0, 1, 2}`

Output:
PRECISION
Class 0 precision: 1
Class 1 precision: 0.8
Class 2 precision: 1

RECALL
Class 0 recall: 1
Class 1 recall: 0.8
Class 2 recall: 1

2023-02-07 18:17 UTC, ken1000minus7 approved these changes
Lgtm

2023-02-08 03:31 UTC, uttammittal02 requested changes

2023-02-08 03:31 UTC, uttammittal02 commented on examples/metrics/precision_eg.cpp
> +        std::cout << "Class " << i << " recall: " << precisionValue[i] << std::endl;
You need to print `" precision "` instead of `" recall "`

2023-02-08 03:46 UTC, uttammittal02 requested changes
Format the files according to the convention. For simplicity, run `./clang-format-all src/` in gitbash(if on widnows)

2023-02-08 06:27 UTC, closed without merging