Classification_report.md Added
PEC-CSS/slowmokit pull request #96
Opened 2023-02-09 13:39 UTC by Modernbeast02

Added the document for classification report.

2023-02-09 14:02 UTC, uttammittal02 requested changes

2023-02-09 14:02 UTC, uttammittal02 commented on docs/methods/metrics/classification_report.md
> +```
Add ss of a sample report

2023-02-09 14:23 UTC, uttammittal02 approved these changes
Lgtm

2023-02-10 04:18 UTC, merged

2023-02-10 04:22 UTC, Ishwarendra requested changes